### ISSUE TITLE
Say Hello

### ISSUE THREAD

**Issue by LuozhuZhang** [skar395/zkSync-projects#4]
Cool! This repo very helpful

May I join u to finish it?

**Comment by Pietro395** [comment]
Hello! of course ! feel free to contribute wih a pull requst 😊

**Comment by LuozhuZhang** [comment]
> Hello! of course ! feel free to contribute wih a pull requst 😊

Great! You can join with me too : https://github.com/LuozhuZhang/awesome-zkevm
